model:
  name: cgnetV2_deformable
  load: ./save/_cgnetV2_deformable_test/best_model_cgnetV2_deformable_Epoch_82.pth
  args:
    in_channels: 3
    out_channels: 3

model_ocr:
  name: ocr
  args:
    load: ./models_ocr_pre_trained/RodoSol-SR

test_dataset:
  dataset:
    name: parallel_training
    args:
      path_split: /kaggle/input/bien-so-xe-project-bao-nho/plate_data_for_training/plate_data_for_training/test_gt.txt
      images_root: /kaggle/input/bien-so-xe-project-bao-nho/plate_data_for_training/plate_data_for_training/test
      phase: testing

  wrapper:
    name: parallel_images_lp
    args:
      imgW: 48
      imgH: 16
      aug: False
      image_aspect_ratio: 3
      background: (0.5, 0.5, 0.5)
      test: True
  batch: 2

